name = "stc-control-plane"

account_id = "15405b0703a8372dfa942f9e685a2903"

main = "worker/auth-gate.js"
compatibility_date = "2026-03-10"

routes = [
  { pattern = "app.securethecloud.dev/*", zone_id = "7e38da83a47554b5e315587a0936f645" }
]

[assets]
directory = "./public"
