name = "stc-control-plane"
type = "javascript"

account_id = "<YOUR_CF_ACCOUNT_ID>"
workers_dev = false

route = "app.securethecloud.dev/*"
zone_id = "<YOUR_ZONE_ID>"

[site]
bucket = "./public"
entry-point = "worker"

[env.production]
workers_dev = false
